#!/bin/sh

player_file_path="../src/"
player_sample_path="../sample/"
check_file="$(ls $player_file_path | grep player_function.c)"
if [ -n $check_file ] 
then
	vim $player_file_path$check_file
else
	cp 
fi
